server:
  port: 8081

spring:
  application:
    name: ulp-account
  datasource:
    name: ulp-account
    url: jdbc:mysql://106.54.98.245:3306/ulp?characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: ww20191226
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: ${REDIS_HOST:106.54.98.245}
    port: ${REDIS_PORT:6379}
    password: "myredispassword"
    sysName: pes-account
    enable: true

mybatis-plus:
  type-aliases-package: com.card.option.pay.entity
  mapper-locations: classpath:com/card/option/pay/mapper/*Mapper.xml

swagger:
  enabled: true
  base-package: com.card.option.pay.controller
  title: cardOption
  version: 1.0.0.SNAPSHOT
  description: 刷卡api
  contact:
    name: card
  terms-of-service-url: http://${spring.cloud.client.ip-address}:${server.port}